behaviors:
  Football:
    trainer_type: ppo
    summary_freq: 50000
    time_horizon: 64
    max_steps: 500000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    threaded: false

    hyperparameters:
      learning_rate: 3e-4
      batch_size: 512
      buffer_size: 10240
      learning_rate_schedule: linear

    network_settings:
      hidden_units: 128
      num_layers: 2
      normalize: false
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      vis_encode_type: simple
      conditioning_type: hyper

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

    self_play:
        save_steps: 50000
        team_change: 250000
        swap_steps: 10000
        play_against_latest_model_ratio: 0.5
        window: 10